"use client";

import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import { store } from "../redux/store";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cosmetics Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <NavBar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
