// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 0,
    img: "/1.jpg",
    name: "johanne-pold-jacobsen-",
    price: 312,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 2,
    img: "/2.jpg",
    name: "laura-chouette",
    price: 235,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 3,
    img: "/28.jpg",
    name: "rob-graph",
    price: 212,
    category: ["skin care", "nail & wax"],
    sale: true,
  },
  {
    id: 4,
    img: "/4.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks", "nail & wax"],
    sale: false,
  },
  {
    id: 5,
    img: "/5.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks", "makeup"],
    sale: false,
  },
  {
    id: 6,
    img: "/26.jpg",
    name: "rob-graph",
    price: 212,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 7,
    img: "/27.jpg",
    name: "rob-graph",
    price: 212,
    category: ["makeup", "nail & wax"],
    sale: false,
  },
  {
    id: 8,
    img: "/8.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks", "makeup"],
    sale: true,
  },
  {
    id: 9,
    img: "/9.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 10,
    img: "/10.jpg",
    name: "rob-graph",
    price: 212,
    category: ["skin care", "nail & wax"],
    sale: false,
  },
  {
    id: 11,
    img: "/11.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks", "skin care"],
    sale: true,
  },
  {
    id: 12,
    img: "/12.jpg",
    name: "rob-graph",
    price: 212,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 13,
    img: "/20.jpg",
    name: "rob-graph",
    price: 212,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 14,
    img: "/14.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks", "skin care"],
    sale: false,
  },
  {
    id: 15,
    img: "/15.jpg",
    name: "rob-graph",
    price: 212,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 16,
    img: "/42.jpg",
    name: "rob-graph",
    price: 212,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 17,
    img: "/43.jpg",
    name: "rob-graph",
    price: 212,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 18,
    img: "/44.jpg",
    name: "rob-graph",
    price: 212,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 19,
    img: "/45.jpg",
    name: "rob-graph",
    price: 212,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 20,
    img: "/46.jpg",
    name: "rob-graph",
    price: 212,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 21,
    img: "/47.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 22,
    img: "/48.jpg",
    name: "rob-graph",
    price: 412,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 23,
    img: "/49.jpg",
    name: "rob-graph",
    price: 232,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 24,
    img: "/50.jpg",
    name: "rob-graph",
    price: 342,
    category: ["makeup", "skin care"],
    sale: false,
  },
  {
    id: 25,
    img: "/51.jpg",
    name: "rob-graph",
    price: 342,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 26,
    img: "/52.jpg",
    name: "rob-graph",
    price: 342,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 27,
    img: "/33.jpg",
    name: "rob-graph",
    price: 342,
    category: ["nail & wax", "skin care", "makeup"],
    sale: false,
  },
  {
    id: 28,
    img: "/41.jpg",
    name: "rob-graph",
    price: 342,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 29,
    img: "/40.jpg",
    name: "rob-graph",
    price: 342,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 30,
    img: "/32.jpg",
    name: "rob-graph",
    price: 342,
    category: ["nail & wax", "skin care"],
    sale: false,
  },
  {
    id: 31,
    img: "/30.jpg",
    name: "rob-graph",
    price: 342,
    category: ["skin care"],
    sale: false,
  },
];
