// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 0,
    img: "/1.jpg",
    name: "johanne-pold-jacobsen-",
    price: 312,
    category: ["lipstricks"],
    sale: false,
  },
  {
    id: 2,
    img: "/2.jpg",
    name: "laura-chouette",
    price: 235,
    category: ["lipstricks"],
    sale: false,
  },
  {
    id: 3,
    img: "/3.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skincare"],
    sale: true,
  },
  {
    id: 4,
    img: "/4.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick"],
    sale: false,
  },
  {
    id: 5,
    img: "/5.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick"],
    sale: false,
  },
  {
    id: 6,
    img: "/6.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skincare"],
    sale: true,
  },
  {
    id: 7,
    img: "/7.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick"],
    sale: false,
  },
  {
    id: 8,
    img: "/8.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick", "Skin care"],
    sale: true,
  },
  {
    id: 9,
    img: "/9.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick"],
    sale: false,
  },
  {
    id: 10,
    img: "/10.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skincare"],
    sale: false,
  },
  {
    id: 11,
    img: "/11.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick", "Skin care"],
    sale: true,
  },
  {
    id: 12,
    img: "/12.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skincare"],
    sale: false,
  },
  {
    id: 13,
    img: "/20.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skincare"],
    sale: true,
  },
  {
    id: 14,
    img: "/14.jpg",
    name: "rob-graph",
    price: 212,
    category: ["lipstick", "Skin care"],
    sale: false,
  },
  {
    id: 15,
    img: "/15.jpg",
    name: "rob-graph",
    price: 212,
    category: ["Skin care"],
    sale: false,
  },
];
